name: toy-ui

on:
  push:
    branches:
      - release
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Build Project
        run: |
          npm install
          npm run deploy