name: toy-ui

on:
  push:
    branches:
      - release
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Build Project
        run: |
          npm install
          npm run docs:build
          
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: docs # 打包的内容放到build分支下
          folder: docs-dist